INSERT INTO adv_calc_option VALUES ('BATTER_G_TARGET', 162);
INSERT INTO adv_calc_option VALUES ('GS_LIMIT', 10);
INSERT INTO adv_calc_option VALUES ('RP_G_TARGET', 10);
INSERT INTO adv_calc_option VALUES ('RP_IP_TARGET', 300);
INSERT INTO adv_calc_option VALUES ('IP_TARGET', 1500);
INSERT INTO adv_calc_option VALUES ('SP_MULTIPLIER', 0.05);
INSERT INTO adv_calc_option VALUES ('RP_MULTIPLIER', 0.15);
INSERT INTO adv_calc_option VALUES ('SP_WITH_ALL_IP', 6);
INSERT INTO adv_calc_option VALUES ('RP_WITH_ALL_IP', 5);