ALTER TABLE team ADD COLUMN num_players INTEGER;
ALTER TABLE team ADD COLUMN spots INTEGER;
ALTER TABLE team ADD COLUMN salaries INTEGER;
ALTER TABLE team ADD COLUMN penalties INTEGER;
ALTER TABLE team ADD COLUMN loans_in INTEGER;
ALTER TABLE team ADD COLUMN loans_out INTEGER;
ALTER TABLE team ADD COLUMN free_cap INTEGER;