ALTER TABLE team ADD COLUMN num_players INTEGER;
ALTER TABLE team ADD COLUMN spots INTEGER;
ALTER TABLE team ADD COLUMN salaries INTEGER;
ALTER TABLE team ADD COLUMN penalties INTEGER;
ALTER TABLE team ADD COLUMN loans_in INTEGER;
ALTER TABLE team ADD COLUMN loans_out INTEGER;
ALTER TABLE team ADD COLUMN free_cap INTEGER;
ALTER TABLE league ADD COLUMN 'platform' VARCHAR(15) DEFAULT 'OTTONEU';
ALTER TABLE league ADD COLUMN 'team_salary_cap' FLOAT DEFAULT 400;
ALTER TABLE league RENAME COLUMN ottoneu_id to site_id;
ALTER TABLE player ADD COLUMN 'yahoo_id' INTEGER;
ALTER TABLE player ADD COLUMN 'mlb_id' INTEGER;
insert into starting_position_set values (1, 'Ottoneu', 'Default Ottoneu Starting Positions');
insert into position_set values (1, 'Ottoneu', 'Current Ottoneu Eligibilities');
ALTER TABLE league ADD COLUMN 'position_set_id' INTEGER DEFAULT 1;
ALTER TABLE value_calculation ADD COLUMN 'position_set_id' INTEGER DEFAULT 1;
ALTER TABLE league ADD COLUMN 'starting_set_id' INTEGER DEFAULT 1;
ALTER TABLE value_calculation ADD COLUMN 'starting_set_id' INTEGER DEFAULT 1;
insert into starting_position values (1, 'POS_C', 1, 1);
insert into starting_position values (2, 'POS_1B', 1, 1);
insert into starting_position values (3, 'POS_2B', 1, 1);
insert into starting_position values (4, 'POS_3B', 1, 1);
insert into starting_position values (5, 'POS_SS', 1, 1);
insert into starting_position values (6, 'POS_MI', 1, 1);
insert into starting_position values (7, 'POS_OF', 5, 1);
insert into starting_position values (8, 'POS_UTIL', 1, 1);
insert into starting_position values (9, 'POS_SP', 5, 1);
insert into starting_position values (10, 'POS_RP', 5, 1);
ALTER TABLE league ADD COLUMN roster_spots int default 40 not null;
ALTER TABLE salary_refresh RENAME COLUMN format to s_format;